/datum/gear/cagsewhite
	display_name = "Cards Against The Galaxy: Special Edition (white deck)"
	path = /obj/item/weapon/deck/cagse
	description = "The ever-popular Cards Against The Galaxy: Special Edition word game. Warning: may include traces of broken fourth wall and obscenity. This is the white deck."

/datum/gear/cagseblack
	display_name = "Cards Against The Galaxy: Special Edition (black deck)"
	path = /obj/item/weapon/deck/cagse/black
	description = "The ever-popular Cards Against The Galaxy: Special Edition word game. Warning: may include traces of broken fourth wall and obscenity. This is the black deck."


// This is a parody of Cards Against Humanity (https://en.wikipedia.org/wiki/Cards_Against_Humanity)
// which is licensed under CC BY-NC-SA 2.0, the full text of which can be found at the following URL:
// https://creativecommons.org/licenses/by-nc-sa/2.0/legalcode

/obj/item/weapon/deck/cagse
	name = "\improper CAG:SE deck (white)"
	desc = "The ever-popular Cards Against The Galaxy: Special Edition word game. Warning: may include traces of broken fourth wall and degeneracy. This is the white deck."
	icon_state = "cag_white"
	var/blanks = 10 //5 extra blank cards than usual to make up for quantity and to encourage antics

/obj/item/weapon/deck/cagse/black
	name = "\improper CAG:SE deck (black)"
	desc = "The ever-popular Cards Against The Galaxy: Special Edition word game. Warning: may include traces of broken fourth wall and degeneracy. This is the black deck."
	icon_state = "cag_black"
	blanks = 0

/obj/item/weapon/deck/cagse/New()
	..()
	var/datum/playingcard/P
	for(var/cardtext in card_text_list)
		P = new()
		P.name = "[cardtext]"
		P.card_icon = "[icon_state]_card"
		P.back_icon = "[icon_state]_card_back"
		cards += P
	if(!blanks)
		return
	for(var/x=1 to blanks)
		P = new()
		P.name = "Blank Card"
		P.card_icon = "[icon_state]_card_back"
		P.back_icon = "[icon_state]_card_back"

//Black Cards
/obj/item/weapon/deck/cagse/black/card_text_list = list(
	"Why am I itchy?",
	"Today, Security shot ____.",
	"The Chaplain this shift is worshiping _____.",
	"Cargo ordered a crate full of _____.",
	"An ERT was called due to ______.",
	"Alert! The Colony Director has armed themselves with _____.",
	"Current Laws: ________ is your master.",
	"Current Laws: ________ is the enemy.",
	"_____ vented the entirety of Cargo.",
	"Today, science found an anomaly that made people ____ and ____.",
	"There was a rap battle between ____ and ____.",
	"Caution, ______ have been detected in collision course with the station.",
	"Today's kitchen menu includes _______.",
	"What did the mercenaries want when they attacked the station?",
	"I think the Colony Director is insane. He just demanded ______ in his office.",
	"Fuckin' scientists, they just turned Misc. Research into _______ .",
	"What's my fetish?",
	"Hello, _______ here with _______",
	"No one else was at _______, they wouldn't understand the ______",
	"Why am I shivering?",
	"What is this world coming to? First, ________, now _______",
	"NanoTrasen's labor union decided to use _____ to raise employee morale.",
	"The Chemist's drug of choice is ______",
	"It is common practice for _______ to ______ on Moghes.",
	"Mercurial Colonies are _____.",
	"The Skrell are celebrating _____ today.",
	"_____ is/are why I'm afraid of the maintenance tunnels.",
	"_____ used ____ to create their newest invention, _____!",
	"Scientists are not allowed to make Gatling _____.",
	"It's not a party until the ____ arrive.",
	"No matter how many Tajaran you have, _____ is never acceptable.",
	"No, the AI's first law is NOT to serve _____.",
	"The robots are not disposal bins for your _____.",
	"You can never have too many _____ on shift.",

	//Above are some custom cards from VOREStation, below are new cards for Special Edition

	"I had a confused boner after the Overseer showed me a video of _____.",
	"Right after being resleeved by the CMO, I was _____.",
	"R&D finally came around and developed _____.",
	"After accidentally touching the supermatter crystal, the first thing I saw in the afterlife was _____.",
	"In order to appear friendlier towards the crew, security officers started offering complimentary _____.",
	"Since nobody ever sets their suit sensors, Medbay has resorted to using _____ as encouragement.",
	"New rule at the bar: _____ is now forbidden.",
	"The bartender fired two beanbag shells into a patron after they were seen doing _____.",
	"After becoming good friends with the Head of Security, they finally let me see their _____ collection.",
	"(Pick 2) ATTENTION: The clown is now wanted for possession of _____ and _____.",
	"After being caught growing ambrosia, the botanist resorted to recreational _____ to cope.",
	"I never expected to find _____ in maintenance.",
	"Nobody was heard from again after _____ escaped from xenobiology.",
	"_____: Everyone does it.",
	"(Pick 2) In exchange for _____, the chef gave me _____.",
	"Due to an operating procedure misunderstanding, security officers have been using _____ to process their prisoners.",
	"The roboticist keeps building cyborgs to satisfy his _____ fetish, instead of building mechs.",
	"Dare dice always ends with _____.",
	"The newest rule for dare dice means that the second lowest roller has to wear nothing but _____.",
	//Official cards below here
	"(Pick 2) Before _____, all we had was_____.",
	"(Pick 2) That's right I killed _____. How, you ask? _____.",
	"What brought the orgy to a grinding halt?",
	"What don't you want to find in your Chinese food?",
	"What has been making life difficult at the nudist colony?",
	"What's that sound?",
	"What's the new fad diet?",
	"(Pick 2) Listen, son. If you want to get involved with _____, I won�t stop you. Just steer clear of _____.",
	"(Pick 2) Having problems with _____? Try _____!",
	"(Pick 2) After months of practice with _____, I think I�m finally ready for _____.",
	"Finally! A service that delivers _____ right to your door."

)

//White Cards
/obj/item/weapon/deck/cagse/var/list/card_text_list = list(
	"Those motherfucking carp",
	"Having sex in the maintenance tunnels",
	"Space 'Nam",
	"Space lesbians",
	"The Gardener getting SUPER high",
	"The Colony Director thinking they're a badass",
	"Being in a cult",
	"Racially biased lawsets",
	"An Unathi who WON'T STOP FIGHTING",
	"Tajaran fetishists",
	"Bald thirty-year-olds",
	"A Chief Engineer who can't setup the engine",
	"Being sucked out into space",
	"Officer Beepsky",
	"Engineering",
	"The grey tide.",
	"The Research Director",
	"Fucking synths",
	"Man-eating purple pod plants",
	"Chemical sprayers filled with lube",
	"Librarians",
	"Squids",
	"Cats",
	"Lizards",
	"Apes",
	"Trees",
	"Supermatter undergarments",
	"Bluespace",
	"Five hundred rabid spiders",
	"Five hundred rabid diona nymphs",
	"Cable ties",
	"Rampant vending machines",
	"Positronic drink coasters",
	"Kitchen utensil anomalies",
	"Locked lockers",
	"Energy spatulas",
	"Flashbang gauntlets",
	"Carp",
	"Space whales",
	"Blu-sharks",
	"Fax machines",
	"Exquisite Pens",
	"Dr. Maxman's male enhancements",
	"Gyrating slimes",
	"Forehead-mounted laser weaponry",
	"Pelvis-mounted laser weaponry",
	"Cardboard cutouts",
	"An obscene amount of rubber ducks",
	"Brain cakes",
	"A drone's game of life.",
	"Anomaly suits",
	"A gardener smoking reishi",
	"Military-grade baseball bats",
	"Barricading the bar",
	"An irritatingly chipper robot",
	"Androids hanging out in the bar drinking beer",
	"Gear harnesses",
	"A seventeen-year-old Colony Director",
	"The throbbing erection that the HoS gets at the thought of shooting something",
	"Trying to stab someone and hugging them instead",
	"Waking up naked in the maintenance tunnels",
	"Horrible cloning accidents",
	"Licking the supermatter due to a dare",
	"A Quartermaster who WON'T STOP ordering guns",
	"Teaching a synthetic the Birds and the Bees",
	"Unnecessary surgery",
	"My addiction to spiders",
	"Wetskrell.nt",
	"DOCTOR MAXMAN!",
	"A group of Skrell getting their squish on",
	"Enough soporific to put the entire station down",
	"Delicious Vietnamese cuisine",

	//Above are some custom cards from VOREStation, below are new cards for Special Edition

	"Upside-down bat cock vore",
	"Wingjobs",
	"The HoP feeding someone to Ian after asking for all access",
	"Being used as fuel instead of being healed by a medihound",
	"Stealing a set of tools",
	"Spying on the dorms with hidden cameras",
	"Stealing all access",
	"Curling up in a belly for hours",
	"Being squeezed down a tight throat",
	"Being forced down the bartender's cock",
	"zip-tying the captain and dragging them into maintenance",
	"Shoving micros down any available orifice",
	"Being shoved down a K9 cyborg's gullet without consent",
	"Tripping in the halls so a medihound eats you",
	"Lying on a table until someone eats you",
	"forgetting your backup implant",
	"Leaving your suit sensors off",
	"Turning your suit sensors to tracking",
	"Giving the clown the spare ID",
	"Happily letting yourself be digested just because someone was hungry",
	"Waking up inside a pair of giant nuts",
	"A shock collar that you can't take off",
	"A size gun without a limiter",
	"Cock vore",
	"A slimy tongue",
	"Being digested into spunk under the bar counter",
	"Maintenance trash pile loot",
	"voring all your friends",
	"Digesting all your friends",
	"Getting fucked from behind right in the bar",
	"Actually using a dorm room",
	"Swallowing enough cum to fill a pool",
	"Giving away the frequency for your shock collar",
	"Ten foot tall sergals",
	"Knotted dog cock",
	"Modular, synthetic, prehensile cocks",
	"Tail maws",
	"Pants pockets",
	"Not wearing anything",
	"Using a nudity permit just because you want to be naked",
	"Nudity",
	"Autofellatio",
	"Clit dicks",
	"Teshari terrorists",
	"Being used as a tap at the bar",
	"Being suffocated by a tight gut",
	"Slurping noises",
	"Listening to someone slowly digest",
	"Not asking if your prey is backup implanted",
	"A person-sized load of cum",
	"Horse cocks",
	"A digested ID card",
	"Canine pussy",
	"Horse pussy",
	"All of medbay being eaten",
	"Getting space aids",
	"Being consumed by a deathclaw",
	"A traitor consuming every last crew member",
	"flooding the hallways with wolf cum",
	"The Skrell doing Skrell things",
	"Slimy xenomorph ovipositors",
	"Lusty xenomorph maids",
	"Steamy bareback sex",
	"Anal beads",
	"Being kidnapped after someone slips neurotoxin into your drink",
	"A woman who surprisingly doesn�t have a penis",
	"A man who surprisingly doesn�t have a penis",
	"Literally xenomorphs",
	"A blowjob",
	"Actually using a condom",
	"Metroids again",
	"Driving cargo tugs around like race cars",
	"Using your fat friend to try and start the singularity engine",
	"A latex maid costume",
	"A realistic xenomorph costume",
	"A seductive bee costume",
	"A cake hat",
	"A smart strapon with ten thousand different shapes and personalities",
	"A condom",
	"Being in a condom",
	"Being a condom",
	"High heels",
	"Thigh high socks",
	"A two-piece swimsuit with just one piece",
	"A traffic cone hat",
	"Crawling into the mouth of someone who's sleeping",
	"A full toolbelt",
	"A dildo",
	"fuzzy cuffs",
	"BDSM",
	"Being constricted by a giant serpent tail",
	"Bulges",
	"A bartender",
	"An EMT",
	"A clown",
	"A person AI",
	"The station AI",
	"Anatomically correct",
	"Toe beans",
	"Paws",
	"Slow digestion",
	"Being nude without a nudity permit",
	"A bag of holding",
	"Falling into someone's drink",
	"Being eaten",
	"Forgetting your backup implant",
	"Hermhub",
	"Ridiculous PDA ringtones",
	"OnlyBeans"

	//And everything beyond this are cards from the original CAH that fit well enough with the other cards

	"A 55-gallon drum of lube.",
	"A cooler full of organs.",
	"A gentle caress of the inner thigh.",
	"A homoerotic volleyball montage.",
	"A hot mess.",
	"A mating display.",
	"A tiny horse.",
	"A zesty breakfast burrito.",
	"An erection that lasts more than four hours.",
	"Anal beads.",
	"Balls.",
	"Basic human decency.",
	"Beating your wives.",
	"Being awesome at sex.",
	"Bitches.",
	"Centaurs.",
	"Civilian casualties.",
	"Daddy issues.",
	"Date rape.",
	"Exactly what you'd expect.",
	"Getting so angry that you pop a boner.",
	"Gloryholes.",
	"Good grammar.",
	"Intimacy problems.",
	"Just the tip.",
	"Lactation.",
	"My hot cousin.",
	"Natural male enhancement.",
	"My vagina.",
	"Panda sex.",
	"Sexting.",
	"Shaft.",
	"Tongue.",
	"A cop who is also a dog.",
	"A vagina that leads to another dimension.",
	"Blowing some dudes in an alley."
)
